# Generated by Django 5.0.2 on 2026-08-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
